# Generated by Django 3.1.3 on 2021-01-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_merge_20180816_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurestatevalue',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
