# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20180907_0313'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'organisation')]),
        ),
    ]
