# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180907_0313'),
        ('environments', '0002_auto_20180809_0014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together=set([('name', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together=set([('identifier', 'environment')]),
        ),
    ]
