# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_has_requested_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
